<a href="https://colab.research.google.com/github/AshokGit544/Document-RAG-Assistant1/blob/main/Document_RAG_Assistant1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip -q install pandas scikit-learn pypdf gradio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 338.8/338.8 kB 6.4 MB/s eta 0:00:00

In [2]:
import re
import json
import pandas as pd
from pathlib import Path
from datetime import datetime
from pypdf import PdfReader
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import files
import gradio as gr

In [3]:
project_dir = Path("Enterprise_Finance_GenAI_Copilot")
project_dir.mkdir(exist_ok=True)

audit_log_path = project_dir / "audit_log.csv"

In [4]:
print("Upload your finance PDF now...")
uploaded = files.upload()

file_path = list(uploaded.keys())[0]
print("Using file:", file_path)

Upload your finance PDF now...

Saving Wells_Fargo_Finance_RAG_Sample_Document.pdf to Wells_Fargo_Finance_RAG_Sample_Document.pdf
Using file: Wells_Fargo_Finance_RAG_Sample_Document.pdf

In [6]:
def load_pdf(path):
    reader = PdfReader(path)
    text = []

    for page in reader.pages:
        page_text = page.extract_text()

        if page_text:
            text.append(page_text)

    return "\n".join(text).strip()

In [7]:
def clean_text(text):
    text = text.replace("■", "-")
    text = text.replace("\x00", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [8]:
raw_text = load_pdf(file_path)
cleaned_text = clean_text(raw_text)

print("Document loaded successfully")
print("Total characters:", len(cleaned_text))

Document loaded successfully
Total characters: 3011

In [9]:
def section_chunk_text(text):
    pattern = r"(?=\d+\.\s+[A-Z])"
    sections = re.split(pattern, text)

    chunks = []

    for section in sections:
        section = section.strip()

        if len(section) > 50:
            chunks.append(section)

    return chunks

In [10]:
chunks = section_chunk_text(cleaned_text)

chunks_df = pd.DataFrame({
    "chunk_id": [f"CHUNK_{i+1:03d}" for i in range(len(chunks))],
    "chunk_text": chunks
})

display(chunks_df)

    chunk_id                                         chunk_text
0  CHUNK_001  Enterprise Finance Operations Guidance Documen...
1  CHUNK_002  1. Introduction This document provides sample ...
2  CHUNK_003  2. Invoice Validation Workflow Finance operati...
3  CHUNK_004  3. Reconciliation Support Guidelines Reconcili...
4  CHUNK_005  4. Customer Escalation Procedures Customer esc...
5  CHUNK_006  5. Risk and Compliance Monitoring Risk monitor...
6  CHUNK_007  6. Access Control and Security Role-based acce...
7  CHUNK_008  7. AI and RAG Usage Guidance Enterprise RAG sy...

In [11]:
def detect_finance_topic(text):
    lower = text.lower()

    if "invoice" in lower:
        return "invoice_operations"
    elif "reconciliation" in lower or "ledger" in lower:
        return "reconciliation"
    elif "customer escalation" in lower or "payment delay" in lower:
        return "customer_support"
    elif "risk" in lower or "compliance" in lower or "aml" in lower:
        return "risk_compliance"
    elif "access control" in lower or "security" in lower or "api keys" in lower:
        return "security_access"
    elif "rag" in lower or "ai-generated" in lower or "source grounding" in lower:
        return "ai_governance"
    else:
        return "general_finance"

In [12]:
chunks_df["finance_topic"] = chunks_df["chunk_text"].apply(detect_finance_topic)
chunks_df["source_file"] = file_path
chunks_df["access_level"] = "finance_user"

display(chunks_df)

,chunk_id,chunk_text,finance_topic,source_file,access_level
0,CHUNK_001,Enterprise Finance Operations Guidance Documen...,general_finance,Wells_Fargo_Finance_RAG_Sample_Document.pdf,finance_user
1,CHUNK_002,1. Introduction This document provides sample ...,invoice_operations,Wells_Fargo_Finance_RAG_Sample_Document.pdf,finance_user
2,CHUNK_003,2. Invoice Validation Workflow Finance operati...,invoice_operations,Wells_Fargo_Finance_RAG_Sample_Document.pdf,finance_user
3,CHUNK_004,3. Reconciliation Support Guidelines Reconcili...,reconciliation,Wells_Fargo_Finance_RAG_Sample_Document.pdf,finance_user
4,CHUNK_005,4. Customer Escalation Procedures Customer esc...,invoice_operations,Wells_Fargo_Finance_RAG_Sample_Document.pdf,finance_user
5,CHUNK_006,5. Risk and Compliance Monitoring Risk monitor...,risk_compliance,Wells_Fargo_Finance_RAG_Sample_Document.pdf,finance_user
6,CHUNK_007,6. Access Control and Security Role-based acce...,invoice_operations,Wells_Fargo_Finance_RAG_Sample_Document.pdf,finance_user
7,CHUNK_008,7. AI and RAG Usage Guidance Enterprise RAG sy...,invoice_operations,Wells_Fargo_Finance_RAG_Sample_Document.pdf,finance_user

In [13]:
USER_ROLE = "finance_user"

In [14]:
def apply_rbac_filter(df, user_role):
    return df[df["access_level"] == user_role].copy()

In [15]:
vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2)
)

tfidf_matrix = vectorizer.fit_transform(chunks_df["chunk_text"])

In [16]:
def detect_query_topic(query):
    lower = query.lower()

    if "invoice" in lower or "vendor" in lower or "purchase order" in lower:
        return "invoice_operations"
    elif "reconciliation" in lower or "ledger" in lower or "transaction" in lower:
        return "reconciliation"
    elif "customer" in lower or "escalation" in lower or "payment delay" in lower:
        return "customer_support"
    elif "risk" in lower or "compliance" in lower or "aml" in lower or "audit" in lower:
        return "risk_compliance"
    elif "access" in lower or "security" in lower or "role" in lower or "api key" in lower:
        return "security_access"
    elif "rag" in lower or "ai" in lower or "grounding" in lower or "fallback" in lower:
        return "ai_governance"
    else:
        return None

In [17]:
def retrieve_chunks(query, top_k=3, min_score=0.10):
    allowed_df = apply_rbac_filter(chunks_df, USER_ROLE)

    query_topic = detect_query_topic(query)

    if query_topic:
        candidate_df = allowed_df[allowed_df["finance_topic"] == query_topic].copy()
    else:
        candidate_df = allowed_df.copy()

    if candidate_df.empty:
        candidate_df = allowed_df.copy()

    candidate_indexes = candidate_df.index.tolist()

    query_vec = vectorizer.transform([query])
    similarity_scores = cosine_similarity(query_vec, tfidf_matrix[candidate_indexes])[0]

    candidate_df["similarity_score"] = similarity_scores

    query_words = set(re.findall(r"\b\w+\b", query.lower()))
    keyword_scores = []

    for text in candidate_df["chunk_text"]:
        text_words = set(re.findall(r"\b\w+\b", text.lower()))
        keyword_match_count = len(query_words.intersection(text_words))
        keyword_scores.append(keyword_match_count)

    candidate_df["keyword_score"] = keyword_scores

    max_keyword_score = candidate_df["keyword_score"].max()

    if max_keyword_score > 0:
        candidate_df["keyword_score_normalized"] = candidate_df["keyword_score"] / max_keyword_score
    else:
        candidate_df["keyword_score_normalized"] = 0

    candidate_df["final_score"] = (
        candidate_df["similarity_score"] * 0.70
        + candidate_df["keyword_score_normalized"] * 0.30
    )

    result = candidate_df.sort_values("final_score", ascending=False).head(top_k)

    result = result[result["similarity_score"] >= min_score]

    result["similarity_percent"] = result["similarity_score"] * 100
    result["final_percent"] = result["final_score"] * 100

    return result.reset_index(drop=True)

In [18]:
def generate_grounded_answer(query, retrieved):
    if retrieved.empty:
        return "The answer is not available in the approved finance document."

    context = " ".join(retrieved["chunk_text"].tolist())
    sentences = re.split(r'(?<=[.!?])\s+', context)

    query_words = set(re.findall(r"\b\w+\b", query.lower()))
    scored_sentences = []

    for sentence in sentences:
        sentence = sentence.strip()

        if len(sentence) < 25:
            continue

        sentence_words = set(re.findall(r"\b\w+\b", sentence.lower()))
        sentence_score = len(query_words.intersection(sentence_words))

        if sentence_score > 0:
            scored_sentences.append((sentence, sentence_score))

    scored_sentences = sorted(scored_sentences, key=lambda x: x[1], reverse=True)

    best_sentences = [sentence for sentence, score in scored_sentences[:3]]

    if not best_sentences:
        return "The answer is not available in the approved finance document."

    return " ".join(best_sentences)

In [19]:
def validate_response(answer):
    if "not available" in answer.lower():
        return "NO_CONTEXT_FOUND"

    if len(answer.strip()) < 20:
        return "LOW_CONFIDENCE"

    return "VALIDATED"

In [20]:
def write_audit_log(question, answer, retrieved, validation_status):
    log_record = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user_role": USER_ROLE,
        "question": question,
        "answer": answer,
        "validation_status": validation_status,
        "retrieved_chunks": ", ".join(retrieved["chunk_id"].tolist()) if not retrieved.empty else "None",
        "topics": ", ".join(retrieved["finance_topic"].tolist()) if not retrieved.empty else "None"
    }

    log_df = pd.DataFrame([log_record])

    if audit_log_path.exists():
        old_df = pd.read_csv(audit_log_path)
        final_df = pd.concat([old_df, log_df], ignore_index=True)
    else:
        final_df = log_df

    final_df.to_csv(audit_log_path, index=False)

In [21]:
def enterprise_finance_rag(question, top_k=3, min_score=0.10):
    retrieved = retrieve_chunks(
        query=question,
        top_k=top_k,
        min_score=min_score
    )

    answer = generate_grounded_answer(question, retrieved)
    validation_status = validate_response(answer)

    write_audit_log(
        question=question,
        answer=answer,
        retrieved=retrieved,
        validation_status=validation_status
    )

    return answer, retrieved, validation_status

In [22]:
test_questions = [
    "How is role-based access control handled?"
]

for question in test_questions:
    answer, retrieved, validation_status = enterprise_finance_rag(question)

    print("\nQUESTION:")
    print(question)

    print("\nANSWER:")
    print(answer)

    print("\nVALIDATION STATUS:")
    print(validation_status)

    print("\nRETRIEVED SOURCE:")
    if not retrieved.empty:
        display(retrieved[[
            "chunk_id",
            "finance_topic",
            "similarity_percent",
            "final_percent",
            "source_file"
        ]])
    else:
        print("No source found.")

QUESTION:
How is role-based access control handled?

ANSWER:
Access Control and Security Role-based access control must be enforced across finance applications. Users should only access authorized financial records, invoices, customer details, and reconciliation reports.

VALIDATION STATUS:
VALIDATED

RETRIEVED SOURCE:

,chunk_id,finance_topic,similarity_percent,final_percent,source_file
0,CHUNK_007,invoice_operations,47.701778,63.391245,Wells_Fargo_Finance_RAG_Sample_Document.pdf

In [23]:
chunks_df.to_csv(project_dir / "finance_document_chunks.csv", index=False)
print("Chunks saved successfully.")

Chunks saved successfully.

In [24]:
def gradio_rag_app(question):
    answer, retrieved, validation_status = enterprise_finance_rag(
        question=question,
        top_k=3,
        min_score=0.10
    )

    if retrieved.empty:
        source_details = "No source found."
    else:
        source_details = retrieved[[
            "chunk_id",
            "finance_topic",
            "similarity_percent",
            "final_percent",
            "source_file"
        ]].to_string(index=False)

    return answer, validation_status, source_details

In [25]:
demo = gr.Interface(
    fn=gradio_rag_app,
    inputs=gr.Textbox(
        label="Ask a finance question",
        lines=2,
        placeholder="Example: What is the invoice validation workflow?"
    ),
    outputs=[
        gr.Textbox(label="Grounded Answer"),
        gr.Textbox(label="Validation Status"),
        gr.Textbox(label="Retrieved Source Details")
    ],
    title="Enterprise Finance GenAI Copilot",
    description="Finance RAG assistant with metadata filtering, RBAC simulation, source grounding, validation, and audit logging."
)

demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://2ac84faddc0dd3e334.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [26]:
audit_df = pd.read_csv(audit_log_path)
display(audit_df)

,timestamp,user_role,question,answer,validation_status,retrieved_chunks,topics
0,2026-05-17 17:43:08,finance_user,How is role-based access control handled?,Access Control and Security Role-based access ...,VALIDATED,CHUNK_007,invoice_operations
1,2026-05-17 17:44:59,finance_user,What should AI-generated responses include?,AI-generated responses must include source gro...,VALIDATED,CHUNK_008,invoice_operations
2,2026-05-17 17:45:16,finance_user,What should AI-generated responses include?,AI-generated responses must include source gro...,VALIDATED,CHUNK_008,invoice_operations